uploader.json, uploader.v2.json
* Adds new spec for the ps -eo pid,ppid,comm command
=> Add command spec for ps -eo command

uploader.json, uploader.v2.json
=> Specs for /etc/ceph/ceph.conf

uploader.json, uploader.v2.json
uploader.json changes for canonical fact collection
=> adding specs for canonical facts

uploader.json, uploader.v2.json
https://github.com/RedHatInsights/insights-core/pull/1558
=> Add specs for proc_stat

uploader.json, uploader.v2.json
https://github.com/RedHatInsights/insights-core/pull/1556
=> Add spec for avc_cache_threshold

uploader.json, uploader.v2.json
https://github.com/RedHatInsights/insights-core/pull/1557
=> Add spec for avc_hash_stats

uploader.json, uploader.v2.json
See https://github.com/RedHatInsights/insights-core/pull/1538
=> Specs for parser LsRVarLibNovaInstances

uploader.json, uploader.v2.json
Parser: https://github.com/RedHatInsights/insights-core/pull/1539
=> Specs for VirtlogdConf

uploader.json, uploader.v2.json
=> Specs for /etc/rabbitmq/rabbitmq-env.conf

uploader.json, uploader.v2.json
=> Add specs for id nova and id nova_migration

uploader.json, uploader.v2.json
=> Add specs for gluster status command

uploader.json, uploader.v2.json
=> Specs for /etc/corosync/corosync.conf

uploader.json, uploader.v2.json
=> Add spec for ifcfg static routes

uploader.json, uploader.v2.json
Added Missing Specs /usr/bin/nmcli dev show
=> Added missing Specs

uploader.json, uploader.v2.json
Parser PR: https://github.com/RedHatInsights/insights-core/pull/1633
=> Added specs for /etc/tuned.conf

uploader.json, uploader.v2.json
https://github.com/RedHatInsights/insights-core/pull/1640
=> Added Specs for numa node

uploader.json, uploader.v2.json
* Replaces #78 to use DataSourceProvider in insights-core instead of ls
command
=> Add datasource for rhev data-center directory

uploader.json, uploader.v2.json
* Add --no-header to command to remove extra output
=> Fix ceph_insights command

uploader.json, uploader.v2.json
Related to https://github.com/RedHatInsights/insights-core/pull/1692
=> RHEL8 - Crypto policies and sshd crypto policy.

uploader.json, uploader.v2.json
=> Specs for /var/log/ironic-inspector/ironic-inspector.log

uploader.json, uploader.v2.json
New specs for file `dhcp_agent.ini`
=> Specs for file dhcp_agent.ini

uploader.json, uploader.v2.json
- since it's changed to use foreach_execute
- https://github.com/RedHatInsights/insights-core/pull/1753
=> Remove the specs of sapcontrol

uploader.json, uploader.v2.json
=> Specs to collect content of /etc/os-release

uploader.json, uploader.v2.json
=> Specs for the command 'ls -ld /var/opt/mssql'

uploader.json, uploader.v2.json
=> Specs for /var/opt/mssql/mssql.conf

uploader.json, uploader.v2.json
related to https://github.com/RedHatInsights/insights-core/pull/1842
=> RHEL8 - crypto policy for bind

uploader.json, uploader.v2.json
=> Specs for the command `subscription-manager facts --list`

uploader.json, uploader.v2.json
* Move the mssql_conf spec to the files section
=> Fix file spec that was put in the commands

uploader.json, uploader.v2.json
New specs for the file `/proc/partitions`
=> Specs for /proc/partitions file

uploader.json, uploader.v2.json
New specs for `/var/log/mistral/executor.log`
=> Specs for /var/log/mistral/executor.log

requirements.txt, validate_json.py
Adding validate_json.py to validate changes to uploader.json and uploader.v2.json before merging.
=> Adding validate_json.py to validate changes to uploader.json and uploader.v2.json before merging.

uploader.json, uploader.v2.json
Added 'yum_list_installed' spec to uploader.json and uploader.v2.json
"/usr/bin/subscription-manager identity"
=> Added 'yum_list_installed' spec to uploader.json and uploader.v2.json

uploader.json, uploader.v2.json
* Convert spec from command to glob to fix regex issue
=> Fix regex in original spec mlx4_port

uploader.json, uploader.v2.json
Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>
=> Remove Spec: httpd_event_V and httpd_worker_V

uploader.json, uploader.v2.json
=> Remove getcert list command

uploader.json, uploader.v2.json
Signed-off-by: Xiangce Liu <xiangceliu@redhat.com>
=> New Spec: boot_loader_entries

uploader.json, uploader.v2.json
=> Add new spec for file /var/log/dmesg

uploader.json, uploader.v2.json
=> Add new command spec for installed product IDs

uploader.json, uploader.v2.json
Signed-off-by: XiaoXue Wang <xiaoxwan@redhat.com>
=> Add new spec for ls_run_systemd_generator

uploader.json, uploader.v2.json
* LsCPU parser: https://github.com/RedHatInsights/insights-core/pull/2135
=> Specs to collect output of the `lscpu` command

uploader.json, uploader.v2.json
=> Add spec "/var/log/foreman/production.log"

uploader.json, uploader.v2.json
=> Specs for the command: gluster peer status

uploader.json, uploader.v2.json
=> New specs for the command: ceph df detail -f json-pretty

uploader.json, uploader.v2.json
=> Remove unused spec for foreman_production_log

uploader.json, uploader.v2.json
Specs has been added to fetch the kernel configs.
=> Updated specs for kernel config

uploader.json, uploader.v2.json
Specs have been added to check the memory used by sockets.
=> Added specs for /proc/net/sockstat

uploader.json, uploader.v2.json
See https://github.com/RedHatInsights/insights-core/issues/1763
=> Add spec for /etc/rhosp-release

uploader.json, uploader.v2.json
=> Specs for /var/log/libvirt/

uploader.json, uploader.v2.json
* Jira: https://projects.engineering.redhat.com/browse/INSPEC-259
=> Fix wrong nginx_conf

uploader.json, uploader.v2.json
The existing spec does not include VXLAN, GRE tunnel stats. Spec has been enhanced to cover the stats. Test cases are added to check the parser.
=> Spec has been modified

uploader.json, uploader.v2.json
New spec for vma_ra_enabled_s390x
Signed-off-by: Xiaonan He <xhe@redhat.com>
=> add new spec for vma_ra_enabled_s390x

uploader.json, uploader.v2.json
New SPEC: kpatch_list
Signed-off-by: shlao <shlao@redhat.com>
=> Add spec command kpatch list

uploader.json, uploader.v2.json
Signed-off-by: Rahul Srivastava rasrivas@redhat.com
=> spec ls_edac_mc

uploader.json, uploader.v2.json
=> Add spec to get MongoDB storage engine

uploader.json, uploader.v2.json
=> Add spec "/etc/foreman-installer/custom-hiera.yaml"

uploader.json, uploader.v2.json
New SPEC: zdump_v
Signed-off-by: shlao <shlao@redhat.com>
=>  Add spec from command zdump -v

uploader.json, uploader.v2.json
Signed-off-by: Ernestas Kulik <ekulik@redhat.com>
=> Add ABRT status spec

uploader.json, uploader.v2.json
=> New specs to collect all files matching /var/log/ceph/ceph.log*

uploader.json, uploader.v2.json
=> Add spec for 'systemctl show *.target'

Jenkinsfile
We need this so we know whether this job fails or succeeds.
Signed-off-by: Stephen Adams <tsadams@gmail.com>
=> Add slack notifications to jenkinsfile

uploader.json, uploader.v2.json
=> Add spec "/proc/sys/kernel/sched_rt_runtime_us"

uploader.json, uploader.v2.json
=> Add spec for "/sys/kernel/debug/sched_features"

uploader.json, uploader.v2.json
=> Add spec for "firewall-cmd --list-all-zones"

uploader.json, uploader.v2.json
=> Add spec "ndctl list -Ni"

uploader.json, uploader.v2.json
=> New spec "/etc/cron.daily/rhsmd"

uploader.json, uploader.v2.json
=> Add spec "/usr/lib/dracut/modules.d/99kdumpbase/kdump-capture.service"

uploader.json, uploader.v2.json
Signed-off-by: Joel Savitz <jsavitz@redhat.com>
=> Add entry for new yum_list_available spec

uploader.json, uploader.v2.json
* Parser PR: https://github.com/RedHatInsights/insights-core/pull/2590/
=> Add specs for '/bin/systemd-analyze blame'

uploader.json, uploader.v2.json
* Fix symbolic name
* Parser changes: https://github.com/RedHatInsights/insights-core/pull/2616
=> [rpm_V_packages] Add 'chrony' package verification

uploader.json, uploader.v2.json
I know I said this wasn't needed, but we could use this collection sooner than we will get it with core collection.
=> adding lvmconfig collection to current client
